return {
    player = {
        y = 512,
        x = 864,
        size = 48,
        speed = 800,
    },
    walls = {
        {
            type = "Sticky",
            vertices = {
                864,
                576,
                1152,
                576,
                1120,
                640,
                800,
                640,
                864,
                576,
            },
            loop = false,
        },
        {
            type = "Death",
            vertices = {
                1216,
                576,
                1408,
                576,
                1376,
                640,
                1184,
                640,
                1216,
                576,
            },
            loop = false,
        },
        {
            type = "Grow",
            vertices = {
                1440,
                576,
                1440,
                480,
                1504,
                480,
                1504,
                576,
                1440,
                576,
            },
            loop = false,
        },
        {
            type = "Clone",
            vertices = {
                768,
                576,
                768,
                480,
            },
            loop = false,
        },
        {
            type = "Goal",
            vertices = {
                320,
                480,
                352,
                608,
                160,
                608,
                160,
                384,
                352,
                384,
                320,
                480,
            },
            loop = false,
        },
    }
}