return {
    player = {
        y = 608,
        x = 864,
        size = 32,
        speed = 800,
    },
    walls = {
        {
            type = "Sticky",
            vertices = {
                32,
                384,
                32,
                64,
                192,
                128,
                128,
                288,
                32,
                384,
            },
            loop = false,
        },
        {
            type = "Icy",
            vertices = {
                64,
                416,
                224,
                288,
                224,
                32,
                416,
                64,
                320,
                384,
                64,
                416,
            },
            loop = false,
        },
        {
            type = "Bounce",
            vertices = {
                352,
                416,
                480,
                128,
                544,
                32,
                992,
                160,
                576,
                416,
                352,
                416,
            },
            loop = false,
        },
        {
            type = "Clone",
            vertices = {
                480,
                320,
                544,
                128,
                832,
                160,
                480,
                320,
            },
            loop = false,
        },
        {
            type = "Shrink",
            vertices = {
                512,
                480,
                64,
                480,
                32,
                832,
                416,
                576,
                192,
                576,
                512,
                480,
            },
            loop = false,
        },
        {
            type = "Grow",
            vertices = {
                480,
                576,
                128,
                896,
                288,
                960,
                480,
                576,
            },
            loop = false,
        },
        {
            type = "Death",
            vertices = {
                512,
                672,
                352,
                992,
                864,
                928,
                512,
                672,
            },
            loop = false,
        },
        {
            type = "Goal",
            vertices = {
                608,
                608,
                736,
                416,
                992,
                288,
                608,
                608,
            },
            loop = false,
        },
    }
}